org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G
android.useAndroidX=true
android.newDsl=false
android.builtInKotlin=true
systemProp.http.connectionTimeout=120000
systemProp.http.socketTimeout=120000
org.gradle.parallel=true
org.gradle.caching=true

# Custom paths to avoid space-character issues in "Hannah Grace Narte"
systemProp.user.home=C\:/android_user_home
systemProp.gradle.user.home=C\:/android_user_home/.gradle
